CREATE TABLE EXAMPLE;

ALTER TABLE EXAMPLE
ADD id int;

INSERT INTO EXAMPLE (id) VALUES (1);
INSERT INTO EXAMPLE (id) VALUES (2);
INSERT INTO EXAMPLE (id) VALUES (3);
INSERT INTO EXAMPLE (id) VALUES (4);
INSERT INTO EXAMPLE (id) VALUES (5);